name: esg-frontier
channels:
  - default
dependencies:
  - python
  - pandas
  - numpy
  - matplotlib
  - tqdm
  - scikit-learn
  - seaborn
  - spacy=3.3.0
  - ipywidgets
  - pip
  - pip:
    - searchtweets-v2==1.1.1